[technote]
id = "SITCOMTN-092"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-092.lsst.io/"
github_url = "https://github.com/lsst-sitcom/sitcomtn-092"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Bruno C.", family = "Quint"}
internal_id = "quintb"
orcid = "https://orcid.org/0000-0002-1557-3560"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
